import net.darkhax.curseforgegradle.*

plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version "${moddev_version}"
    id 'idea'
    id 'net.darkhax.curseforgegradle' version "${cursegradle_plugin_version}"
    id 'com.modrinth.minotaur' version "${modrinth_plugin_version}"
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = mod_version
group = mod_group_id

repositories {
    mavenLocal()
    maven {
        name 'Configuration'
        url 'https://repo.repsy.io/mvn/toma/public/'
    }
    flatDir {
        dir './library'
    }
}

base {
    archivesName = "${mod_id}-${minecraft_version}"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

neoForge {
    version = project.neo_version

    accessTransformers = project.files('src/main/templates/META-INF/accesstransformer.cfg')

    runs {
        client {
            client()

            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    // Configuration
    implementation "dev.toma.configuration:configuration-${project.libraries_mc_version}:${project.configuration}-neoforge"

    // Core library
    implementation name: "tarkovcraft_core-${libraries_mc_version}-${core}"
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description,
            configuration          : configuration,
            configuration_range    : configuration_range,
            core                   : core,
            core_range             : core_range
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}

sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.register('publishToCurseForge', TaskPublishCurseForge) {
    dependsOn(tasks.jar)
    apiToken = project.hasProperty("CURSEFORGE_TOKEN") ? project.findProperty("CURSEFORGE_TOKEN").toString() : ""
    debugMode = debug.toBoolean()

    def uploadFile = upload(curseforge_project_id, tasks.jar.archiveFile)
    uploadFile.changelogType = Constants.CHANGELOG_MARKDOWN
    uploadFile.changelog = file("./CHANGELOG.md").exists() ? file('./CHANGELOG.md') : "-- No changelog provided --"
    uploadFile.releaseType = getReleaseChannel()
    uploadFile.displayName = "${mod_id}-neoforge-${minecraft_version}-${version}"
    uploadFile.addModLoader('NeoForge')
    uploadFile.addEnvironment('Client', 'Server')
    uploadFile.addJavaVersion("Java 25")
    uploadFile.addRequirement("configuration")
    uploadFile.addRequirement("tarkovcraft-core")
    compatible_mc_versions.split(",").each { gameVersion ->
        uploadFile.addGameVersion(gameVersion)
    }
}

List compatibleVersions = compatible_mc_versions.split(",")
modrinth {
    token.set(project.hasProperty("MODRINTH_TOKEN") ? project.findProperty("MODRINTH_TOKEN").toString() : "")
    projectId.set(modrinth_project_id)
    versionNumber.set("${version}")
    versionName.set("${mod_id}-neoforge-${minecraft_version}-${version}")
    versionType.set(getReleaseChannel())
    uploadFile.set(jar)
    gameVersions.set(compatibleVersions)
    debugMode.set(debug.toBoolean())
    changelog.set(
            providers.provider {
                def changelogFile = file("./CHANGELOG.md")
                changelogFile.exists() ? changelogFile.text : "-- No changelog provided --"
            }
    )
    loaders.set(["neoforge"])
    dependencies {
        required.project("configuration")
        required.project("tarkovcraft-core")
    }
}
tasks.modrinth.dependsOn(tasks.jar)

tasks.register('publishMod') {
    group = "publishing"
}
tasks.publishMod.dependsOn(tasks.publishToCurseForge, tasks.modrinth)

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}

def isPublishing() {
    gradle.startParameter.taskNames.any { it.toLowerCase().contains('publish') }
}

def getReleaseChannel() {
    def versionString = version.toString()
    if (versionString.contains("beta")) {
        return Constants.RELEASE_TYPE_BETA
    } else if (versionString.contains("alpha")) {
        return Constants.RELEASE_TYPE_ALPHA
    } else if (versionString.contains("dev")) {
        if (isPublishing())
            throw new GradleException("Attempted to publish development version: " + versionString)
        return null
    } else {
        return Constants.RELEASE_TYPE_RELEASE
    }
}