name: Discord notification
on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - "Publish"
    types:
      - completed

jobs:
  sendNotification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Changelog
        id: changelog
        uses: Toma1O6/file-read-action@v1
        with:
          file: "CHANGELOG.md"
          max-lines: '31'
          max-chars: '4096'

      - name: Webhook
        env:
          WEBHOOK: ${{ secrets.WEBHOOK_URL }}
          CHANGELOG: ${{ steps.changelog.outputs.content }}
        run: |
          jq -n \
          --arg snippet "$CHANGELOG" \
            '{
              username: "Release bot",
              avatar_url: "https://cdn.discordapp.com/avatars/1308464796831711244/e886df028da3a37ad84b05e3fb0c3b8b.webp?size=32",
              content: "<@&1373296070574080070>",
              embeds: [
                {
                  title: "Medical System",
                  url: "https://github.com/T-T-Team/TarkovCraft-HealthSystem",
                  description: ($snippet),
                  color: 5434377,
                  thumbnail: { url: "https://media.forgecdn.net/avatars/1278/936/638831812718332860.png" },
                  fields: [
                    {
                      name: "CurseForge",
                      value: "[Download](<https://www.curseforge.com/minecraft/mc-mods/med-system>)",
                      inline: true
                    },
                    {
                      name: "Modrinth",
                      value: "[Download](<https://modrinth.com/mod/med-system>)",
                      inline: true
                    },
                    {
                      name: "Sources",
                      value: "[GitHub](<https://github.com/T-T-Team/TarkovCraft-HealthSystem>)",
                      inline: true
                    },
                    {
                      name: "Support",
                      value: "[Patreon](<https://www.patreon.com/c/tnt_team>)",
                      inline: false
                    },
                    {
                      name: "Report issue",
                      value: "[GitHub](<https://github.com/T-T-Team/TarkovCraft-HealthSystem/issues>)",
                      inline: false
                    }
                  ],
                  footer: { text: "CurseForge file may take up to 1 hour to be published" }
                }
              ]
            }' > payload.json
          
          curl "$WEBHOOK" \
            -H "Content-Type: application/json" \
            --data @payload.json