name: Publish
on:
  push:
    tags:
      - 'version/*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Prepare Gradle Wrapper
        run: chmod +x ./gradlew

      - uses: gradle/actions/setup-gradle@v4

      - name: Release
        run: ./gradlew publishMod -PCURSEFORGE_TOKEN=${{ secrets.CF_TOKEN }} -PMODRINTH_TOKEN=${{ secrets.MODRINTH_TOKEN }} -PMAVEN_PUBLIC_URL=${{ secrets.MAVEN_URL }} -PMAVEN_USERNAME=${{ secrets.MAVEN_USER }} -PMAVEN_PASSWORD=${{ secrets.MAVEN_PASS }} --no-configuration-cache

      - uses: Toma1O6/file-read-action@v1
        id: changelog
        with:
          file: "CHANGELOG.md"
          max-chars: '4096'

      - uses: T-T-Team/discord-release-announcement-action@v1.0.1
        with:
          webhookUrl: ${{ secrets.WEBHOOK_URL }}
          message: '<@&1373296070574080070>'
          title: "Medical System"
          homepage: "https://github.com/T-T-Team/TarkovCraft-HealthSystem"
          changelog: ${{ steps.changelog.outputs.content }}
          color: '5434377'
          iconUrl: 'https://media.forgecdn.net/avatars/1477/880/638959828952676637.png'
          note: 'CurseForge file may take up to 1 hour to be published'
          curseForgeUrl: 'https://www.curseforge.com/minecraft/mc-mods/med-system'
          modrinthUrl: 'https://modrinth.com/mod/med-system'
          sourcesUrl: 'https://github.com/T-T-Team/TarkovCraft-HealthSystem'
          issueTrackerUrl: 'https://github.com/T-T-Team/TarkovCraft-HealthSystem/issues'
          wikiUrl: 'https://github.com/T-T-Team/TarkovCraft-Documentation/wiki'
          donationUrl: 'https://www.patreon.com/c/tnt_team'